name: Build IPA
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Исправлено на v4 для поддержки новых правил GitHub

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # Мы не пишем версию вручную, чтобы сервер сам выбрал совместимую с твоим кодом

      - name: Install dependencies
        run: flutter pub get # Здесь больше не будет ошибки "version solving failed"

      - name: Build iOS
        run: flutter build ios --release --no-codesign # Собираем файл для Scarlet

      - name: Create IPA Structure
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload
          zip -r app.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Исправлено на v4, чтобы убрать ошибку "deprecated version"
        with:
          name: music-app-final
          path: app.ipa
